<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class GDP_Lite_Field_Builder {
 private static $instance=null;
 public static function instance(){ if(null===self::$instance){self::$instance=new self();} return self::$instance; }
 public function register_hooks(){ add_action('admin_menu',array($this,'menu')); add_action('admin_post_gdp_save_field',array($this,'save')); add_action('admin_post_gdp_delete_field',array($this,'delete')); }
 public function menu(){ add_submenu_page('edit.php?post_type=gdp_game',__('Fields','gdp-lite'),__('Fields','gdp-lite'),'manage_gdp_fields','gdp-fields',array($this,'render')); }
 public function render(){ if(!current_user_can('manage_gdp_fields')){wp_die(esc_html__('Permission denied.','gdp-lite'));} $fields=get_option('gdp_registered_fields',array()); ?>
 <div class="wrap"><h1><?php esc_html_e('Dynamic Fields','gdp-lite');?></h1><p><?php esc_html_e('Create fields used automatically by the editor, query engine, REST API, imports, exports, templates and blocks.','gdp-lite');?></p>
 <table class="widefat striped"><thead><tr><th><?php esc_html_e('Label','gdp-lite');?></th><th><?php esc_html_e('Name','gdp-lite');?></th><th><?php esc_html_e('Type','gdp-lite');?></th><th><?php esc_html_e('Capabilities','gdp-lite');?></th><th></th></tr></thead><tbody>
 <?php foreach($fields as $f): ?><tr><td><?php echo esc_html($f['label']??'');?></td><td><code><?php echo esc_html($f['name']??'');?></code></td><td><?php echo esc_html($f['type']??'text');?></td><td><?php echo esc_html(implode(', ',array_keys(array_filter(array_intersect_key($f,array_flip(array('searchable','filterable','rest','import','export','card','single','archive')))))));?></td><td><a class="button-link-delete" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=gdp_delete_field&name='.rawurlencode($f['name'])),'gdp_delete_field_'.$f['name']));?>"><?php esc_html_e('Delete','gdp-lite');?></a></td></tr><?php endforeach; ?>
 </tbody></table><hr><h2><?php esc_html_e('Add Field','gdp-lite');?></h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="gdp_save_field"><?php wp_nonce_field('gdp_save_field');?><table class="form-table"><tr><th><label for="gdp-label"><?php esc_html_e('Label','gdp-lite');?></label></th><td><input class="regular-text" id="gdp-label" name="label" required></td></tr><tr><th><label for="gdp-name"><?php esc_html_e('Name','gdp-lite');?></label></th><td><input class="regular-text" id="gdp-name" name="name" required pattern="[a-z0-9_\-]+"></td></tr><tr><th><?php esc_html_e('Type','gdp-lite');?></th><td><select name="type"><?php foreach(GDP_Lite_Field_Validator::supported_types() as $type):?><option value="<?php echo esc_attr($type);?>"><?php echo esc_html($type);?></option><?php endforeach;?></select></td></tr><tr><th><?php esc_html_e('Options','gdp-lite');?></th><td><?php foreach(array('searchable','filterable','rest','import','export','card','single','archive') as $flag):?><label style="margin-right:14px"><input type="checkbox" name="flags[]" value="<?php echo esc_attr($flag);?>" <?php checked(in_array($flag,array('rest','import','export','single'),true));?>> <?php echo esc_html($flag);?></label><?php endforeach;?></td></tr></table><?php submit_button(__('Add Field','gdp-lite'));?></form></div><?php }
 public function save(){ if(!current_user_can('manage_gdp_fields')||!check_admin_referer('gdp_save_field')){wp_die(esc_html__('Permission denied.','gdp-lite'));} $name=sanitize_key(wp_unslash($_POST['name']??'')); if(!$name){wp_die(esc_html__('A field name is required.','gdp-lite'));} $flags=array_map('sanitize_key',(array)($_POST['flags']??array())); $def=array('name'=>$name,'label'=>sanitize_text_field(wp_unslash($_POST['label']??$name)),'type'=>sanitize_key(wp_unslash($_POST['type']??'text')),'active'=>true); foreach(array('searchable','filterable','rest','import','export','card','single','archive') as $flag){$def[$flag]=in_array($flag,$flags,true);} $all=get_option('gdp_registered_fields',array()); $all[$name]=$def; update_option('gdp_registered_fields',$all,false); GDP()->fields()->bump_version(); wp_safe_redirect(admin_url('edit.php?post_type=gdp_game&page=gdp-fields')); exit; }
 public function delete(){ $name=sanitize_key(wp_unslash($_GET['name']??'')); if(!current_user_can('manage_gdp_fields')||!wp_verify_nonce(wp_unslash($_GET['_wpnonce']??''),'gdp_delete_field_'.$name)){wp_die(esc_html__('Permission denied.','gdp-lite'));} $all=get_option('gdp_registered_fields',array()); unset($all[$name]); update_option('gdp_registered_fields',$all,false); GDP()->fields()->bump_version(); wp_safe_redirect(admin_url('edit.php?post_type=gdp_game&page=gdp-fields')); exit; }
}
