<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class GDP_Lite_Query {
 private $args=array(); private $query;
 public function __construct($args=array()){ $this->args=$this->normalize(is_array($args)?$args:array()); $wp=$this->build($this->args); $wp=apply_filters('gdp_after_build_query',$wp,$this->args,$this); do_action('gdp_before_build_query',$this->args,$this); $key=gdp_cache()->key('dynamic_query',array('args'=>$wp,'fields'=>GDP()->fields()->version(),'locale'=>determine_locale())); $found=false; $cached=gdp_cache()->enabled()&&'rand'!==$this->args['orderby']?gdp_cache()->get($key,$found):false; if($found&&is_array($cached)){ $ids=array_map('absint',$cached['ids']??array()); $this->query=new WP_Query(array('post_type'=>'gdp_game','post_status'=>'publish','post__in'=>$ids?:array(0),'posts_per_page'=>$ids?count($ids):1,'orderby'=>'post__in','no_found_rows'=>true)); $this->query->found_posts=(int)($cached['found_posts']??count($ids)); $this->query->max_num_pages=(int)($cached['max_num_pages']??1); } else { $this->query=new WP_Query($wp); if(gdp_cache()->enabled()&&'rand'!==$this->args['orderby']){gdp_cache()->set($key,array('ids'=>wp_list_pluck($this->query->posts,'ID'),'found_posts'=>$this->query->found_posts,'max_num_pages'=>$this->query->max_num_pages));}} do_action('gdp_after_query',$this->query,$this->args,$this); }
 private function normalize($a){ $d=array('type'=>'','provider'=>'','collection'=>'','category'=>'','search'=>'','fields'=>array(),'field_relation'=>'AND','limit'=>12,'offset'=>0,'paged'=>1,'orderby'=>'date','order'=>'DESC','post_status'=>'publish'); $a=wp_parse_args($a,$d); foreach(array('rtp_min','rtp_max','max_win_min','volatility','featured') as $legacy){if(array_key_exists($legacy,$a)&&''!==$a[$legacy]&&null!==$a[$legacy]){$map=array('rtp_min'=>array('rtp','>='),'rtp_max'=>array('rtp','<='),'max_win_min'=>array('max_win','>='),'volatility'=>array('volatility','='),'featured'=>array('featured','=') ); [$n,$c]=$map[$legacy]; $a['fields'][$n]=array('value'=>$a[$legacy],'compare'=>$c);}} $a['limit']=max(1,min(100,absint($a['limit']))); $a['paged']=max(1,absint($a['paged'])); $a['order']='ASC'===strtoupper($a['order'])?'ASC':'DESC'; $a['field_relation']='OR'===strtoupper($a['field_relation'])?'OR':'AND'; return apply_filters('gdp_query_fields',$a,$this); }
 private function build($a){ $wp=array('post_type'=>'gdp_game','post_status'=>$a['post_status'],'posts_per_page'=>$a['limit'],'offset'=>absint($a['offset']),'paged'=>$a['paged'],'order'=>$a['order'],'ignore_sticky_posts'=>true,'s'=>sanitize_text_field($a['search'])); $tax=array(); foreach(array('type'=>'gdp_game_type','provider'=>'gdp_provider','collection'=>'gdp_collection','category'=>'gdp_game_category') as $k=>$t){if(!empty($a[$k])){$tax[]=array('taxonomy'=>$t,'field'=>'slug','terms'=>array_map('sanitize_title',(array)$a[$k]));}} if($tax){$tax['relation']='AND';$wp['tax_query']=$tax;} $meta=array('relation'=>$a['field_relation']); foreach((array)$a['fields'] as $name=>$condition){$field=GDP()->fields()->get($name); if(!$field||!$field->get('filterable',false)){continue;} $meta[]=$this->meta_clause($field,$condition);} if(count($meta)>1){$wp['meta_query']=apply_filters('gdp_query_meta',$meta,$a,$this);} $orderby=sanitize_key($a['orderby']); if(in_array($orderby,array('date','modified','title','menu_order','rand'),true)){$wp['orderby']=$orderby;} elseif('popular'===$orderby){$wp['meta_key']='_gdp_views';$wp['orderby']='meta_value_num';} elseif($field=GDP()->fields()->get($orderby)){ $wp['meta_key']=$field->meta_key(); $wp['orderby']=in_array($field->type(),array('number','decimal','switch'),true)?'meta_value_num':'meta_value'; } else {$wp['orderby']='date';} return apply_filters('gdp_query_orderby',$wp,$a,$this); }
 private function meta_clause($field,$condition){ $c=array('key'=>$field->meta_key()); if(!is_array($condition)){$condition=array('value'=>$condition,'compare'=>'=');} if(isset($condition['between'])){$condition['value']=$condition['between'];$condition['compare']='BETWEEN';} if(isset($condition['in'])){$condition['value']=$condition['in'];$condition['compare']='IN';} if(isset($condition['like'])){$condition['value']=$condition['like'];$condition['compare']='LIKE';} if(isset($condition['exists'])){$condition['compare']=$condition['exists']?'EXISTS':'NOT EXISTS';} $c['compare']=strtoupper($condition['compare']??'='); if(isset($condition['value'])){$c['value']=$condition['value'];} $c['type']=in_array($field->type(),array('number','decimal','switch'),true)?'NUMERIC':('date'===$field->type()?'DATE':'CHAR'); return $c; }
 public function get_query(){return $this->query;} public function get_posts(){return $this->query->posts;} public function have_posts(){return $this->query->have_posts();} public function the_post(){return $this->query->the_post();} public function found_posts(){return (int)$this->query->found_posts;} public function max_num_pages(){return (int)$this->query->max_num_pages;} public function get_args(){return $this->args;}
 public static function aggregate($field_name,$operation='count',$args=array()){ global $wpdb; $field=GDP()->fields()->get($field_name); if(!$field){return null;} $allowed=array('count'=>'COUNT','min'=>'MIN','max'=>'MAX','avg'=>'AVG','sum'=>'SUM'); $fn=$allowed[strtolower($operation)]??'COUNT'; $ids=(new self($args+array('limit'=>100,'paged'=>1)))->get_posts(); $ids=array_map(static function($p){return (int)$p->ID;},$ids); if(!$ids){return 0;} $in=implode(',',array_fill(0,count($ids),'%d')); $sql="SELECT {$fn}(CAST(meta_value AS DECIMAL(20,6))) FROM {$wpdb->postmeta} WHERE meta_key=%s AND post_id IN ($in)"; return (float)$wpdb->get_var($wpdb->prepare($sql,array_merge(array($field->meta_key()),$ids))); }
}
