<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class GDP_Lite_Template_Engine {
 private static $instance=null; public static function instance(){if(null===self::$instance){self::$instance=new self();}return self::$instance;} public function register_hooks(){}
 public function format($field,$value){ if(''===$value||null===$value){return '';} switch($field->type()){case 'decimal': return number_format_i18n((float)$value,2).('%'=== $field->get('format')?'%':''); case 'switch': return $value?__('Yes','gdp-lite'):__('No','gdp-lite'); case 'date': $t=strtotime($value); return $t?date_i18n(get_option('date_format'),$t):$value; case 'url': return esc_url($value); default:return is_array($value)?implode(', ',$value):(string)$value;} }
 public function render_field($name,$post_id=0,$args=array()){ $field=GDP()->fields()->get($name); if(!$field){return '';} $post_id=$post_id?:get_the_ID(); $value=GDP()->fields()->get_value($post_id,$name); $formatted=$this->format($field,$value); if(''===$formatted){return '';} $args=wp_parse_args($args,array('show_label'=>true,'context'=>'single','class'=>'')); $html='<div class="gdp-field gdp-field-'.esc_attr($name).' '.esc_attr($args['class']).'">'; if($args['show_label']){$html.='<span class="gdp-field-label">'.esc_html($field->get('label')).'</span>';} if('url'===$field->type()){$html.='<a class="gdp-field-value" href="'.esc_url($value).'" rel="nofollow">'.esc_html($formatted).'</a>';} else {$html.='<span class="gdp-field-value">'.esc_html($formatted).'</span>';} return apply_filters('gdp_field_output',$html.'</div>',$field,$value,$post_id,$args); }
 public function render_group($context='single',$post_id=0){$html=''; foreach(GDP()->fields()->all() as $field){if($field->get($context,false)){$html.=$this->render_field($field->name(),$post_id,array('context'=>$context));}} return '<div class="gdp-dynamic-fields gdp-context-'.esc_attr($context).'">'.$html.'</div>';}
 public function render_card($post_id=0){$post_id=$post_id?:get_the_ID(); if(GDP()->builder()){return '<article class="gdp-game-card">'.GDP()->builder()->render('card',$post_id).'</article>';} return '';}
}
